const translations = {
  fr: {
    "nav.about": "Maison",
    "nav.products": "Produits",
    "nav.services": "Services",
    "nav.export": "Export",
    "nav.contact": "Contact",
    "hero.eyebrow": "Exportateur agro-alimentaire algerien",
    "hero.title": "Les saveurs authentiques d'Algerie, preparees pour le monde.",
    "hero.copy":
      "Djabel Amana Agro accompagne les producteurs et les marques locales vers les marches internationaux avec une approche fiable, soignee et orientee qualite.",
    "hero.ctaPrimary": "Demander une offre",
    "hero.ctaSecondary": "Voir les produits",
    "hero.badgeOne": "Fondee en 2023",
    "hero.badgeTwo": "Bir Mourad Rais, Alger",
    "hero.badgeThree": "Trading et accompagnement export",
    "about.kicker": "A propos",
    "about.title": "Un partenaire agile pour l'export agro-alimentaire.",
    "about.body":
      "Nous sommes specialises dans l'exportation de produits alimentaires de haute qualite vers les pays du monde. Notre reseau relie des producteurs algeriens de confiance a des acheteurs qui recherchent des produits fiables, competitifs et authentiques.",
    "about.metricOne": "annee de creation",
    "about.metricTwo": "equipe specialisee",
    "about.metricThree": "sourcing algerien",
    "products.kicker": "Produits",
    "products.title": "Selection agro-alimentaire pour l'export.",
    "products.subtitle": "Une offre claire, adaptee aux distributeurs, importateurs et partenaires commerciaux.",
    "products.dates.category": "Produit phare",
    "products.dates.name": "Dattes Deglet Nour",
    "products.dates.description": "Dattes algeriennes selectionnees pour leur texture, leur douceur et leur presentation export.",
    "products.olive.category": "En vrac et au detail",
    "products.olive.name": "Huile d'olive",
    "products.olive.description": "Huile d'olive algerienne disponible en vrac pour les professionnels et au detail pour les circuits de distribution.",
    "products.vegetables.category": "Frais et saisonnier",
    "products.vegetables.name": "Fruits et legumes",
    "products.vegetables.description": "Produits frais organises selon les besoins saisonniers, les volumes et les marches cibles.",
    "products.honey.category": "Saveurs authentiques",
    "products.honey.name": "Miel et specialites",
    "products.honey.description": "Produits de terroir valorises par un positionnement authentique et une presentation soignee.",
    "services.kicker": "Services",
    "services.title": "Du sourcing a la relation commerciale durable.",
    "services.subtitle": "Une methode construite autour de la confiance, de l'integrite et du benefice mutuel.",
    "services.trading.title": "Trading agro-alimentaire",
    "services.trading.body": "Identification, negociation et coordination des opportunites export.",
    "services.support.title": "Accompagnement des entreprises",
    "services.support.body": "Support, conseil et developpement commercial pour les marches etrangers.",
    "services.quality.title": "Controle et preparation",
    "services.quality.body": "Selection, emballage et verification selon les attentes internationales.",
    "export.kicker": "Process export",
    "export.title": "Preparation, palettes, documents et chargement securise.",
    "export.body":
      "Chaque expedition est organisee avec soin afin de renforcer la presence du Made in Algeria sur les marches etrangers, notamment en Europe.",
    "export.stepOne": "Selection",
    "export.stepTwo": "Conditionnement",
    "export.stepThree": "Documents",
    "export.stepFour": "Expedition",
    "gallery.kicker": "Presence digitale",
    "gallery.title": "Photos et videos publiques de Djabel Amana Agro.",
    "gallery.subtitle": "Une selection de medias publics issus de LinkedIn et Facebook, avec des liens directs vers les comptes officiels.",
    "gallery.linkedIn": "Suivre sur LinkedIn",
    "gallery.instagram": "Voir Instagram",
    "gallery.facebook": "Voir Facebook",
    "contact.kicker": "Contact",
    "contact.title": "Construisons votre prochaine operation export.",
    "contact.address": "Bir Mourad Rais 16078, Algerie"
  },
  en: {
    "nav.about": "Home",
    "nav.products": "Products",
    "nav.services": "Services",
    "nav.export": "Export",
    "nav.contact": "Contact",
    "hero.eyebrow": "Algerian agro-food exporter",
    "hero.title": "Authentic Algerian flavors, prepared for the world.",
    "hero.copy":
      "Djabel Amana Agro supports local producers and brands as they reach international markets with a reliable, careful, quality-focused approach.",
    "hero.ctaPrimary": "Request an offer",
    "hero.ctaSecondary": "View products",
    "hero.badgeOne": "Founded in 2023",
    "hero.badgeTwo": "Bir Mourad Rais, Algiers",
    "hero.badgeThree": "Trading and export support",
    "about.kicker": "About",
    "about.title": "An agile partner for agro-food export.",
    "about.body":
      "We specialize in exporting high-quality food products to countries around the world. Our network connects trusted Algerian producers with buyers looking for reliable, competitive and authentic products.",
    "about.metricOne": "year founded",
    "about.metricTwo": "specialized team",
    "about.metricThree": "Algerian sourcing",
    "products.kicker": "Products",
    "products.title": "Agro-food selection for export.",
    "products.subtitle": "A clear offer designed for distributors, importers and commercial partners.",
    "products.dates.category": "Signature product",
    "products.dates.name": "Deglet Nour dates",
    "products.dates.description": "Algerian dates selected for texture, sweetness and export-ready presentation.",
    "products.olive.category": "Bulk and retail",
    "products.olive.name": "Olive oil",
    "products.olive.description": "Algerian olive oil available in bulk for professionals and in retail-ready formats for distribution channels.",
    "products.vegetables.category": "Fresh and seasonal",
    "products.vegetables.name": "Fruits and vegetables",
    "products.vegetables.description": "Fresh products organized around seasonal needs, volumes and target markets.",
    "products.honey.category": "Authentic flavors",
    "products.honey.name": "Honey and specialties",
    "products.honey.description": "Local specialties positioned with authenticity and polished presentation.",
    "services.kicker": "Services",
    "services.title": "From sourcing to lasting commercial relationships.",
    "services.subtitle": "A method built around trust, integrity and mutual benefit.",
    "services.trading.title": "Agro-food trading",
    "services.trading.body": "Identification, negotiation and coordination of export opportunities.",
    "services.support.title": "Company support",
    "services.support.body": "Guidance, consulting and business development for foreign markets.",
    "services.quality.title": "Control and preparation",
    "services.quality.body": "Selection, packaging and verification according to international expectations.",
    "export.kicker": "Export process",
    "export.title": "Preparation, pallets, documents and secure loading.",
    "export.body":
      "Every shipment is organized with care to strengthen the presence of Made in Algeria across foreign markets, especially in Europe.",
    "export.stepOne": "Selection",
    "export.stepTwo": "Packaging",
    "export.stepThree": "Documents",
    "export.stepFour": "Shipment",
    "gallery.kicker": "Digital presence",
    "gallery.title": "Public photos and videos from Djabel Amana Agro.",
    "gallery.subtitle": "A selection of public media from LinkedIn and Facebook, with direct links to the official accounts.",
    "gallery.linkedIn": "Follow on LinkedIn",
    "gallery.instagram": "View Instagram",
    "gallery.facebook": "View Facebook",
    "contact.kicker": "Contact",
    "contact.title": "Let us build your next export operation.",
    "contact.address": "Bir Mourad Rais 16078, Algeria"
  },
  es: {
    "nav.about": "Inicio",
    "nav.products": "Productos",
    "nav.services": "Servicios",
    "nav.export": "Exportacion",
    "nav.contact": "Contacto",
    "hero.eyebrow": "Exportador agroalimentario argelino",
    "hero.title": "Sabores autenticos de Argelia, preparados para el mundo.",
    "hero.copy":
      "Djabel Amana Agro acompana a productores y marcas locales hacia mercados internacionales con un enfoque fiable, cuidadoso y orientado a la calidad.",
    "hero.ctaPrimary": "Solicitar oferta",
    "hero.ctaSecondary": "Ver productos",
    "hero.badgeOne": "Fundada en 2023",
    "hero.badgeTwo": "Bir Mourad Rais, Argel",
    "hero.badgeThree": "Trading y apoyo exportador",
    "about.kicker": "Empresa",
    "about.title": "Un socio agil para la exportacion agroalimentaria.",
    "about.body":
      "Nos especializamos en exportar productos alimentarios de alta calidad a paises de todo el mundo. Nuestra red conecta productores argelinos de confianza con compradores que buscan productos fiables, competitivos y autenticos.",
    "about.metricOne": "ano de creacion",
    "about.metricTwo": "equipo especializado",
    "about.metricThree": "origen argelino",
    "products.kicker": "Productos",
    "products.title": "Seleccion agroalimentaria para exportacion.",
    "products.subtitle": "Una oferta clara para distribuidores, importadores y socios comerciales.",
    "products.dates.category": "Producto estrella",
    "products.dates.name": "Datiles Deglet Nour",
    "products.dates.description": "Datiles argelinos seleccionados por su textura, dulzura y presentacion para exportacion.",
    "products.olive.category": "A granel y al detalle",
    "products.olive.name": "Aceite de oliva",
    "products.olive.description": "Aceite de oliva argelino disponible a granel para profesionales y al detalle para canales de distribucion.",
    "products.vegetables.category": "Fresco y estacional",
    "products.vegetables.name": "Frutas y verduras",
    "products.vegetables.description": "Productos frescos organizados segun temporada, volumenes y mercados objetivo.",
    "products.honey.category": "Sabores autenticos",
    "products.honey.name": "Miel y especialidades",
    "products.honey.description": "Productos locales valorizados con autenticidad y una presentacion cuidada.",
    "services.kicker": "Servicios",
    "services.title": "Del abastecimiento a relaciones comerciales duraderas.",
    "services.subtitle": "Un metodo basado en confianza, integridad y beneficio mutuo.",
    "services.trading.title": "Trading agroalimentario",
    "services.trading.body": "Identificacion, negociacion y coordinacion de oportunidades de exportacion.",
    "services.support.title": "Apoyo a empresas",
    "services.support.body": "Asesoria, orientacion y desarrollo comercial para mercados extranjeros.",
    "services.quality.title": "Control y preparacion",
    "services.quality.body": "Seleccion, embalaje y verificacion segun expectativas internacionales.",
    "export.kicker": "Proceso exportador",
    "export.title": "Preparacion, palets, documentos y carga segura.",
    "export.body":
      "Cada envio se organiza cuidadosamente para reforzar la presencia del Made in Algeria en mercados extranjeros, especialmente en Europa.",
    "export.stepOne": "Seleccion",
    "export.stepTwo": "Embalaje",
    "export.stepThree": "Documentos",
    "export.stepFour": "Envio",
    "gallery.kicker": "Presencia digital",
    "gallery.title": "Fotos y videos publicos de Djabel Amana Agro.",
    "gallery.subtitle": "Una seleccion de medios publicos de LinkedIn y Facebook, con enlaces directos a las cuentas oficiales.",
    "gallery.linkedIn": "Seguir en LinkedIn",
    "gallery.instagram": "Ver Instagram",
    "gallery.facebook": "Ver Facebook",
    "contact.kicker": "Contacto",
    "contact.title": "Construyamos su proxima operacion de exportacion.",
    "contact.address": "Bir Mourad Rais 16078, Argelia"
  },
  ar: {
    "nav.about": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.services": "الخدمات",
    "nav.export": "التصدير",
    "nav.contact": "اتصال",
    "hero.eyebrow": "مصدر جزائري للمنتجات الزراعية والغذائية",
    "hero.title": "نكهات جزائرية اصيلة جاهزة للعالم.",
    "hero.copy":
      "ترافق دجابل امانة اغرو المنتجين والعلامات المحلية نحو الاسواق الدولية بمنهج موثوق ومنظم يركز على الجودة.",
    "hero.ctaPrimary": "اطلب عرضا",
    "hero.ctaSecondary": "شاهد المنتجات",
    "hero.badgeOne": "تاسست سنة 2023",
    "hero.badgeTwo": "بئر مراد رايس، الجزائر",
    "hero.badgeThree": "تجارة ودعم للتصدير",
    "about.kicker": "من نحن",
    "about.title": "شريك مرن لتصدير المنتجات الزراعية والغذائية.",
    "about.body":
      "نحن متخصصون في تصدير منتجات غذائية عالية الجودة الى دول العالم. تربط شبكتنا المنتجين الجزائريين الموثوقين بمشترين يبحثون عن منتجات موثوقة وتنافسية واصيلة.",
    "about.metricOne": "سنة التأسيس",
    "about.metricTwo": "فريق متخصص",
    "about.metricThree": "مصادر جزائرية",
    "products.kicker": "المنتجات",
    "products.title": "تشكيلة غذائية زراعية موجهة للتصدير.",
    "products.subtitle": "عرض واضح للموزعين والمستوردين والشركاء التجاريين.",
    "products.dates.category": "منتج رئيسي",
    "products.dates.name": "تمور دقلة نور",
    "products.dates.description": "تمور جزائرية مختارة لقوامها وحلاوتها وجاهزيتها للعرض في اسواق التصدير.",
    "products.olive.category": "بالجملة وبالتجزئة",
    "products.olive.name": "زيت الزيتون",
    "products.olive.description": "زيت زيتون جزائري متوفر بالجملة للمهنيين وبالتجزئة لقنوات التوزيع.",
    "products.vegetables.category": "طازج وموسمي",
    "products.vegetables.name": "فواكه وخضروات",
    "products.vegetables.description": "منتجات طازجة منظمة حسب الموسم والكميات والاسواق المستهدفة.",
    "products.honey.category": "نكهات اصيلة",
    "products.honey.name": "عسل ومنتجات خاصة",
    "products.honey.description": "منتجات محلية بقيمة اصيلة وتقديم احترافي.",
    "services.kicker": "الخدمات",
    "services.title": "من اختيار المصادر الى علاقات تجارية طويلة الامد.",
    "services.subtitle": "منهج مبني على الثقة والنزاهة والمنفعة المتبادلة.",
    "services.trading.title": "تجارة المنتجات الزراعية والغذائية",
    "services.trading.body": "تحديد فرص التصدير والتفاوض عليها وتنسيقها.",
    "services.support.title": "مرافقة الشركات",
    "services.support.body": "دعم واستشارة وتطوير تجاري للاسواق الخارجية.",
    "services.quality.title": "المراقبة والتحضير",
    "services.quality.body": "اختيار وتعبئة ومراجعة وفق متطلبات الاسواق الدولية.",
    "export.kicker": "مسار التصدير",
    "export.title": "تحضير، منصات شحن، وثائق، وتحميل آمن.",
    "export.body":
      "تنظم كل شحنة بعناية لتعزيز حضور المنتج الجزائري في الاسواق الخارجية، خاصة في اوروبا.",
    "export.stepOne": "اختيار",
    "export.stepTwo": "تعبئة",
    "export.stepThree": "وثائق",
    "export.stepFour": "شحن",
    "gallery.kicker": "الحضور الرقمي",
    "gallery.title": "صور وفيديوهات عامة من دجابل امانة اغرو.",
    "gallery.subtitle": "اختيار من الوسائط العامة المنشورة على لينكدان وفيسبوك، مع روابط مباشرة للحسابات الرسمية.",
    "gallery.linkedIn": "تابعنا على لينكدان",
    "gallery.instagram": "شاهد انستغرام",
    "gallery.facebook": "شاهد فيسبوك",
    "contact.kicker": "اتصال",
    "contact.title": "لنبن معا عملية التصدير القادمة.",
    "contact.address": "بئر مراد رايس 16078، الجزائر"
  }
};

const root = document.documentElement;
const buttons = document.querySelectorAll(".lang-btn");
const nodes = document.querySelectorAll("[data-i18n]");

function setLanguage(lang) {
  const dictionary = translations[lang] || translations.fr;
  root.lang = lang;
  root.dir = lang === "ar" ? "rtl" : "ltr";

  nodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) node.textContent = dictionary[key];
  });

  buttons.forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });

  localStorage.setItem("djabel-amana-language", lang);
}

buttons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(localStorage.getItem("djabel-amana-language") || "fr");
